// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rlrs.proto

/*
Package qiqi_rlrs is a generated protocol buffer package.

It is generated from these files:
	rlrs.proto

It has these top-level messages:
	MsgUserItem
	ReqGetRoomUserList
	RspGetRoomUserList
	ReqQueryRoomUserInfo
	RspQueryRoomUserInfo
	ReqRlrsMsg
	RspRlrsMsg
*/
package qiqi_rlrs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// 包命令定义
type ENUM_RLRS_CMD int32

const (
	ENUM_RLRS_CMD_enum_rlrs_get_room_user_list   ENUM_RLRS_CMD = 1
	ENUM_RLRS_CMD_enum_rlrs_query_room_user_info ENUM_RLRS_CMD = 2
)

var ENUM_RLRS_CMD_name = map[int32]string{
	1: "enum_rlrs_get_room_user_list",
	2: "enum_rlrs_query_room_user_info",
}
var ENUM_RLRS_CMD_value = map[string]int32{
	"enum_rlrs_get_room_user_list":   1,
	"enum_rlrs_query_room_user_info": 2,
}

func (x ENUM_RLRS_CMD) Enum() *ENUM_RLRS_CMD {
	p := new(ENUM_RLRS_CMD)
	*p = x
	return p
}
func (x ENUM_RLRS_CMD) String() string {
	return proto.EnumName(ENUM_RLRS_CMD_name, int32(x))
}
func (x *ENUM_RLRS_CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ENUM_RLRS_CMD_value, data, "ENUM_RLRS_CMD")
	if err != nil {
		return err
	}
	*x = ENUM_RLRS_CMD(value)
	return nil
}
func (ENUM_RLRS_CMD) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 用户数据项
type MsgUserItem struct {
	Int64Userid      *int64 `protobuf:"varint,1,opt,name=int64_userid" json:"int64_userid,omitempty"`
	Int64EnterTime   *int64 `protobuf:"varint,2,opt,name=int64_enter_time" json:"int64_enter_time,omitempty"`
	Int32ManagerRole *int32 `protobuf:"varint,3,opt,name=int32_manager_role" json:"int32_manager_role,omitempty"`
	Int32StarLevel   *int32 `protobuf:"varint,4,opt,name=int32_star_level" json:"int32_star_level,omitempty"`
	Int32NobleLevel  *int32 `protobuf:"varint,5,opt,name=int32_noble_level" json:"int32_noble_level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgUserItem) Reset()                    { *m = MsgUserItem{} }
func (m *MsgUserItem) String() string            { return proto.CompactTextString(m) }
func (*MsgUserItem) ProtoMessage()               {}
func (*MsgUserItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgUserItem) GetInt64Userid() int64 {
	if m != nil && m.Int64Userid != nil {
		return *m.Int64Userid
	}
	return 0
}

func (m *MsgUserItem) GetInt64EnterTime() int64 {
	if m != nil && m.Int64EnterTime != nil {
		return *m.Int64EnterTime
	}
	return 0
}

func (m *MsgUserItem) GetInt32ManagerRole() int32 {
	if m != nil && m.Int32ManagerRole != nil {
		return *m.Int32ManagerRole
	}
	return 0
}

func (m *MsgUserItem) GetInt32StarLevel() int32 {
	if m != nil && m.Int32StarLevel != nil {
		return *m.Int32StarLevel
	}
	return 0
}

func (m *MsgUserItem) GetInt32NobleLevel() int32 {
	if m != nil && m.Int32NobleLevel != nil {
		return *m.Int32NobleLevel
	}
	return 0
}

// --------------------------------------------------------------------------------------------------------------------------------
// 获取房间用户列表请求
type ReqGetRoomUserList struct {
	Int64LastUserid  *int64 `protobuf:"varint,1,opt,name=int64_last_userid" json:"int64_last_userid,omitempty"`
	Int32Robot       *int32 `protobuf:"varint,2,opt,name=int32_robot" json:"int32_robot,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqGetRoomUserList) Reset()                    { *m = ReqGetRoomUserList{} }
func (m *ReqGetRoomUserList) String() string            { return proto.CompactTextString(m) }
func (*ReqGetRoomUserList) ProtoMessage()               {}
func (*ReqGetRoomUserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReqGetRoomUserList) GetInt64LastUserid() int64 {
	if m != nil && m.Int64LastUserid != nil {
		return *m.Int64LastUserid
	}
	return 0
}

func (m *ReqGetRoomUserList) GetInt32Robot() int32 {
	if m != nil && m.Int32Robot != nil {
		return *m.Int32Robot
	}
	return 0
}

// 获取房间用户列表应答
type RspGetRoomUserList struct {
	Int32Total       *int32         `protobuf:"varint,1,opt,name=int32_total" json:"int32_total,omitempty"`
	Int64LastUserid  *int64         `protobuf:"varint,2,opt,name=int64_last_userid" json:"int64_last_userid,omitempty"`
	OUserList        []*MsgUserItem `protobuf:"bytes,3,rep,name=o_user_list" json:"o_user_list,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RspGetRoomUserList) Reset()                    { *m = RspGetRoomUserList{} }
func (m *RspGetRoomUserList) String() string            { return proto.CompactTextString(m) }
func (*RspGetRoomUserList) ProtoMessage()               {}
func (*RspGetRoomUserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RspGetRoomUserList) GetInt32Total() int32 {
	if m != nil && m.Int32Total != nil {
		return *m.Int32Total
	}
	return 0
}

func (m *RspGetRoomUserList) GetInt64LastUserid() int64 {
	if m != nil && m.Int64LastUserid != nil {
		return *m.Int64LastUserid
	}
	return 0
}

func (m *RspGetRoomUserList) GetOUserList() []*MsgUserItem {
	if m != nil {
		return m.OUserList
	}
	return nil
}

// 查询房间指定用户信息请求
type ReqQueryRoomUserInfo struct {
	Int64Userid      *int64 `protobuf:"varint,1,opt,name=int64_userid" json:"int64_userid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqQueryRoomUserInfo) Reset()                    { *m = ReqQueryRoomUserInfo{} }
func (m *ReqQueryRoomUserInfo) String() string            { return proto.CompactTextString(m) }
func (*ReqQueryRoomUserInfo) ProtoMessage()               {}
func (*ReqQueryRoomUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReqQueryRoomUserInfo) GetInt64Userid() int64 {
	if m != nil && m.Int64Userid != nil {
		return *m.Int64Userid
	}
	return 0
}

// 查询房间指定用户信息应答
type RspQueryRoomUserInfo struct {
	OUserItem        *MsgUserItem `protobuf:"bytes,1,opt,name=o_user_item" json:"o_user_item,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspQueryRoomUserInfo) Reset()                    { *m = RspQueryRoomUserInfo{} }
func (m *RspQueryRoomUserInfo) String() string            { return proto.CompactTextString(m) }
func (*RspQueryRoomUserInfo) ProtoMessage()               {}
func (*RspQueryRoomUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RspQueryRoomUserInfo) GetOUserItem() *MsgUserItem {
	if m != nil {
		return m.OUserItem
	}
	return nil
}

// 请求消息
type ReqRlrsMsg struct {
	Uint32Cmd        *uint32               `protobuf:"varint,1,opt,name=uint32_cmd" json:"uint32_cmd,omitempty"`
	Uint64Jobid      *uint64               `protobuf:"varint,2,opt,name=uint64_jobid" json:"uint64_jobid,omitempty"`
	Int64Roomid      *int64                `protobuf:"varint,3,opt,name=int64_roomid" json:"int64_roomid,omitempty"`
	OGetUserList     *ReqGetRoomUserList   `protobuf:"bytes,4,opt,name=o_get_user_list" json:"o_get_user_list,omitempty"`
	OQueryUserInfo   *ReqQueryRoomUserInfo `protobuf:"bytes,5,opt,name=o_query_user_info" json:"o_query_user_info,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ReqRlrsMsg) Reset()                    { *m = ReqRlrsMsg{} }
func (m *ReqRlrsMsg) String() string            { return proto.CompactTextString(m) }
func (*ReqRlrsMsg) ProtoMessage()               {}
func (*ReqRlrsMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReqRlrsMsg) GetUint32Cmd() uint32 {
	if m != nil && m.Uint32Cmd != nil {
		return *m.Uint32Cmd
	}
	return 0
}

func (m *ReqRlrsMsg) GetUint64Jobid() uint64 {
	if m != nil && m.Uint64Jobid != nil {
		return *m.Uint64Jobid
	}
	return 0
}

func (m *ReqRlrsMsg) GetInt64Roomid() int64 {
	if m != nil && m.Int64Roomid != nil {
		return *m.Int64Roomid
	}
	return 0
}

func (m *ReqRlrsMsg) GetOGetUserList() *ReqGetRoomUserList {
	if m != nil {
		return m.OGetUserList
	}
	return nil
}

func (m *ReqRlrsMsg) GetOQueryUserInfo() *ReqQueryRoomUserInfo {
	if m != nil {
		return m.OQueryUserInfo
	}
	return nil
}

// 应答消息
type RspRlrsMsg struct {
	Uint32Cmd        *uint32               `protobuf:"varint,1,opt,name=uint32_cmd" json:"uint32_cmd,omitempty"`
	Uint64Jobid      *uint64               `protobuf:"varint,2,opt,name=uint64_jobid" json:"uint64_jobid,omitempty"`
	Int64Roomid      *int64                `protobuf:"varint,3,opt,name=int64_roomid" json:"int64_roomid,omitempty"`
	OGetUserList     *RspGetRoomUserList   `protobuf:"bytes,4,opt,name=o_get_user_list" json:"o_get_user_list,omitempty"`
	OQueryUserInfo   *RspQueryRoomUserInfo `protobuf:"bytes,5,opt,name=o_query_user_info" json:"o_query_user_info,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *RspRlrsMsg) Reset()                    { *m = RspRlrsMsg{} }
func (m *RspRlrsMsg) String() string            { return proto.CompactTextString(m) }
func (*RspRlrsMsg) ProtoMessage()               {}
func (*RspRlrsMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RspRlrsMsg) GetUint32Cmd() uint32 {
	if m != nil && m.Uint32Cmd != nil {
		return *m.Uint32Cmd
	}
	return 0
}

func (m *RspRlrsMsg) GetUint64Jobid() uint64 {
	if m != nil && m.Uint64Jobid != nil {
		return *m.Uint64Jobid
	}
	return 0
}

func (m *RspRlrsMsg) GetInt64Roomid() int64 {
	if m != nil && m.Int64Roomid != nil {
		return *m.Int64Roomid
	}
	return 0
}

func (m *RspRlrsMsg) GetOGetUserList() *RspGetRoomUserList {
	if m != nil {
		return m.OGetUserList
	}
	return nil
}

func (m *RspRlrsMsg) GetOQueryUserInfo() *RspQueryRoomUserInfo {
	if m != nil {
		return m.OQueryUserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgUserItem)(nil), "qiqi.rlrs.msg_user_item")
	proto.RegisterType((*ReqGetRoomUserList)(nil), "qiqi.rlrs.req_get_room_user_list")
	proto.RegisterType((*RspGetRoomUserList)(nil), "qiqi.rlrs.rsp_get_room_user_list")
	proto.RegisterType((*ReqQueryRoomUserInfo)(nil), "qiqi.rlrs.req_query_room_user_info")
	proto.RegisterType((*RspQueryRoomUserInfo)(nil), "qiqi.rlrs.rsp_query_room_user_info")
	proto.RegisterType((*ReqRlrsMsg)(nil), "qiqi.rlrs.req_rlrs_msg")
	proto.RegisterType((*RspRlrsMsg)(nil), "qiqi.rlrs.rsp_rlrs_msg")
	proto.RegisterEnum("qiqi.rlrs.ENUM_RLRS_CMD", ENUM_RLRS_CMD_name, ENUM_RLRS_CMD_value)
}

func init() { proto.RegisterFile("rlrs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0x9a, 0xe6, 0xc0, 0xa4, 0x15, 0xad, 0x41, 0x95, 0x41, 0x08, 0x85, 0x70, 0xa9, 0x90,
	0x88, 0x50, 0x5a, 0xf5, 0xc0, 0x81, 0x0b, 0x20, 0x81, 0x44, 0x39, 0x14, 0xf5, 0x6c, 0xa5, 0xd4,
	0x44, 0x46, 0x76, 0xdc, 0xd8, 0x0e, 0x88, 0xb7, 0xe0, 0xb9, 0xf6, 0xa9, 0x56, 0xb6, 0xa3, 0xa6,
	0xdd, 0x4d, 0x57, 0x7b, 0xda, 0xeb, 0x7c, 0xfe, 0xfe, 0x66, 0x0c, 0xa0, 0xb8, 0xd2, 0xd9, 0x41,
	0x49, 0x23, 0xd1, 0xa3, 0x9a, 0xd5, 0x2c, 0xb3, 0x83, 0xf4, 0x7f, 0x00, 0x63, 0xa1, 0x4b, 0xd2,
	0x68, 0xaa, 0x08, 0x33, 0x54, 0xa0, 0xa7, 0x30, 0x62, 0x95, 0x59, 0x2d, 0xdd, 0x88, 0xed, 0x71,
	0x90, 0x04, 0xf3, 0x10, 0x61, 0x98, 0xf8, 0x29, 0xad, 0x0c, 0x55, 0xc4, 0x30, 0x41, 0xf1, 0xc0,
	0x21, 0xcf, 0x01, 0xb1, 0xca, 0x2c, 0x72, 0x22, 0x8a, 0xaa, 0x28, 0xa9, 0x22, 0x4a, 0x72, 0x8a,
	0xc3, 0x24, 0x98, 0x47, 0x2d, 0x6b, 0x91, 0x13, 0x6d, 0x0a, 0x45, 0x38, 0xfd, 0x43, 0x39, 0x1e,
	0x3a, 0xe4, 0x19, 0x4c, 0x3d, 0x52, 0xc9, 0x1d, 0xa7, 0x2d, 0x14, 0x59, 0x28, 0xfd, 0x02, 0x33,
	0x45, 0x6b, 0x52, 0x52, 0x43, 0x94, 0x94, 0xc2, 0x47, 0xe3, 0x4c, 0x9b, 0x96, 0xb4, 0x5a, 0x12,
	0x5e, 0x68, 0x73, 0x9e, 0xef, 0x09, 0xc4, 0x5e, 0x4f, 0xc9, 0x9d, 0x34, 0x2e, 0x5a, 0x94, 0xfe,
	0x85, 0x99, 0xd2, 0x87, 0x3e, 0xa5, 0xe3, 0x73, 0x23, 0x4d, 0xc1, 0x9d, 0x46, 0xd4, 0x2f, 0xef,
	0x4b, 0xbe, 0x85, 0x58, 0x76, 0x74, 0x1c, 0x26, 0xe1, 0x3c, 0xce, 0x71, 0x76, 0xdc, 0x63, 0x76,
	0xb6, 0xc3, 0xf4, 0x1d, 0x60, 0x5b, 0xa1, 0x6e, 0xa8, 0xfa, 0x77, 0x62, 0xcd, 0xaa, 0x5f, 0xb2,
	0x7f, 0xbf, 0xe9, 0x57, 0xc0, 0x36, 0x6a, 0x2f, 0xa3, 0x33, 0xb7, 0xe2, 0x8e, 0x70, 0x97, 0xf9,
	0x55, 0x00, 0x23, 0xeb, 0x6e, 0x21, 0x22, 0x74, 0x89, 0x10, 0x40, 0xe3, 0xdb, 0xfe, 0x14, 0xde,
	0x6f, 0x6c, 0x53, 0x34, 0x3e, 0xc6, 0x6f, 0xb9, 0x6b, 0x6b, 0x0e, 0xbb, 0x6c, 0x36, 0x01, 0xdb,
	0xbb, 0x2b, 0x86, 0xe8, 0x3d, 0x3c, 0x96, 0x6e, 0x89, 0xdd, 0x02, 0x86, 0x2e, 0xc3, 0xab, 0x93,
	0x0c, 0x17, 0x4e, 0xf6, 0x01, 0xa6, 0xb2, 0x6d, 0x75, 0x2c, 0xe4, 0xee, 0x1c, 0xe7, 0xaf, 0x6f,
	0xb0, 0xfb, 0xba, 0xfb, 0x32, 0xfa, 0xf0, 0xd0, 0x65, 0xfa, 0x7f, 0xcd, 0x7d, 0xcb, 0x5c, 0x38,
	0xe4, 0x9b, 0x2d, 0x8c, 0x3f, 0x7f, 0xdf, 0xae, 0xc9, 0xe6, 0xdb, 0xe6, 0x07, 0xf9, 0xb8, 0xfe,
	0x84, 0x12, 0x78, 0x41, 0xab, 0x46, 0xf8, 0x76, 0xb7, 0x0d, 0x27, 0x01, 0x4a, 0xe1, 0x65, 0xf7,
	0xa2, 0x4f, 0x74, 0x32, 0xb8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x21, 0xae, 0x39, 0xb2, 0xdb, 0x03,
	0x00, 0x00,
}
